USE MusicService

TRUNCATE TABLE Accounts
TRUNCATE TABLE Albums
TRUNCATE TABLE Albums_Genres
TRUNCATE TABLE Albums_Sertifications
TRUNCATE TABLE Artists
TRUNCATE TABLE Artists_Albums
TRUNCATE TABLE Artists_Songs
TRUNCATE TABLE Genres
TRUNCATE TABLE Groups
TRUNCATE TABLE Groups_Albums
TRUNCATE TABLE Groups_Artists
TRUNCATE TABLE Groups_Songs
TRUNCATE TABLE Logs
TRUNCATE TABLE Permission
TRUNCATE TABLE Related_accounts
TRUNCATE TABLE Roles
TRUNCATE TABLE Roles_Permissions
TRUNCATE TABLE Sertifications
TRUNCATE TABLE Songs
TRUNCATE TABLE Songs_Genres
TRUNCATE TABLE Songs_Sertifications
TRUNCATE TABLE Visitors